- hosts: localhost
  gather_facts: no

  vars_files:
  - metadata.json

  tasks:
  - name: 'Compute resource names'
    set_fact:
      cluster_id_tag: "openshiftClusterID={{ infraID }}"
      primary_cluster_network_tag: "{{ infraID }}-primaryClusterNetwork"
      os_infra_id: "{{ infraID }}"
      os_network: "{{ infraID }}-network"
      os_subnet: "{{ infraID }}-nodes"
      os_router: "{{ infraID }}-external-router"
      # Port names
      os_port_api: "{{ infraID }}-api-port"
      os_port_ingress: "{{ infraID }}-ingress-port"
      os_port_bootstrap: "{{ infraID }}-bootstrap-port"
      os_port_controlplane: "{{ infraID }}-controlplane-port"
      os_port_worker: "{{ infraID }}-worker-port"
      # Security groups names
      os_sg_controlplane: "{{ infraID }}-controlplane"
      os_sg_worker: "{{ infraID }}-worker"
      os_sg_infra: "{{ infraID }}-infra"
      os_sg_api: "{{ infraID }}-api"
      os_sg_ingress: "{{ infraID }}-ingress"
      os_sg_ssh: "{{ infraID }}-ssh"
      # Server names
      os_bootstrap_server_name: "{{ infraID }}-bootstrap"
      os_cp_server_name: "{{ infraID }}-controlplane"
      os_cp_server_group_name: "{{ infraID }}-controlplane"
      os_compute_server_name: "{{ infraID }}-worker"
      # Trunk names
      os_cp_trunk_name: "{{ infraID }}-controlplane-trunk"
      os_compute_trunk_name: "{{ infraID }}-worker-trunk"
      # Subnet pool name
      subnet_pool: "{{ infraID }}-kuryr-pod-subnetpool"
      # Service network name
      os_svc_network: "{{ infraID }}-kuryr-service-network"
      # Service subnet name
      os_svc_subnet: "{{ infraID }}-kuryr-service-subnet"
      # Ignition files
      os_bootstrap_ignition: "{{ infraID }}-bootstrap-ignition.json"

  - name: 'Net2 Compute resource names'
    set_fact:
      os_net2_network_tag: "{{ infraID }}-net2Network"
      os_net2_network: "{{ infraID }}-net2-network"
      os_net2_subnet: "{{ infraID }}-net2-nodes"
      os_net2_router: "{{ infraID }}-net2-external-router"
      # Port names
      os_net2_port_ingress: "{{ infraID }}-net2-ingress-port"     
      # Security groups names
      os_net2_sg_worker: "{{ infraID }}-net2-worker"
      os_net2_sg_ingress: "{{ infraID }}-net2-ingress"
