- hosts: localhost
  tasks:
  - name: Remove server groups
    openstack.cloud.server_group:
      state: absent
      name: "{{ item }}"
    loop:
    - "{{ custID }}-worker-default"
    - "{{ custID }}-infra"
    - "{{ custID }}-controlplane"

  - name: Remove net2 server group
    openstack.cloud.server_group:
      state: absent
      name: "{{ custID }}-worker-net2"
    when: net2 | default(false) | bool
