- hosts: localhost
  tasks:
  - name: Remove server groups
    openstack.cloud.server_group:
      state: absent
      name: "{{ item }}"
    loop:
    - "worker-default"
    - "infra"
    - "controlplane"
