# Required Python packages:
#
# ansible
# openstacksdk

- import_playbook: common.yaml

- hosts: all
  gather_facts: no

  tasks:
  - name: Register infra ID variable
    command: jq -r .infraID metadata.json
    register: infrastructureID

  - name: Remove bastion server
    os_server:
      name: "{{ infrastructureID.stdout }}-bastion"
      state: absent

  - name: Remove bastion server port
    os_port:
      name: "{{ infrastructureID.stdout }}-bastion-port"
      state: absent
