- hosts: localhost
  tasks:
  - name: Remove server groups
    openstack.cloud.server_group:
      state: absent
      name: "{{ item }}"
    loop:
    - "worker-default"
    - "infra"
    - "controlplane"

  - name: Remove net2 server group
    openstack.cloud.server_group:
      state: absent
      name: "worker-net2"
    when: net2 | default(false) | bool
