# Required Python packages:
#
# ansible
# openstackclient
# openstacksdk

- import_playbook: common.yaml
- import_playbook: eg-common.yaml

- hosts: all
  gather_facts: no

  tasks:
  - name: 'Create the Extra Gateway ingress security group'
    os_security_group:
      name: "{{ os_eg_sg_ingress }}"
    when: os_eg_ingress_fip is defined and os_eg_ingress_fip|length>0

  - name: 'Set EG ingress security group tag'
    command:
      cmd: "openstack security group set --tag {{ cluster_id_tag }} {{ os_eg_sg_ingress }} "
    when: os_eg_ingress_fip is defined and os_eg_ingress_fip|length>0

  - name: 'Create eg-ingress-sg rule "Extra Gateway Ingress HTTP external"'
    os_security_group_rule:
      security_group: "{{ os_eg_sg_ingress }}"
      remote_ip_prefix: "{{ item }}"
      protocol: tcp
      port_range_min: 80
      port_range_max: 80
    loop: "{{ egIngressAllowedSourcesForPriNet }}"
    when: os_eg_ingress_fip is defined and os_eg_ingress_fip|length>0    

  - name: 'Create eg-ingress-sg rule "Extra Gateway Igress HTTPS external"'
    os_security_group_rule:
      security_group: "{{ os_eg_sg_ingress }}"
      remote_ip_prefix: "{{ item }}"
      protocol: tcp
      port_range_min: 443
      port_range_max: 443
    loop: "{{ egIngressAllowedSourcesForPriNet }}"
    when: os_eg_ingress_fip is defined and os_eg_ingress_fip|length>0    
