- hosts: localhost
  tasks:
  - name: Create default worker server group
    openstack.cloud.server_group:
      state: present
      name: "{{ custID }}-worker-default"
      policies:
      - soft-anti-affinity
    register: workerDefault

  - name: Create infra server group
    openstack.cloud.server_group:
      state: present
      name: "{{ custID }}-infra"
      policies:
      - anti-affinity
    register: infraGroup

  - name: Create controlplane server group
    openstack.cloud.server_group:
      state: present
      name: "{{ custID }}-controlplane"
      policies:
      - anti-affinity
    register: controlplaneGroup 

  - name: Create net2 worker server group
    openstack.cloud.server_group:
      state: present
      name: "{{ custID }}-worker-net2"
      policies:
      - soft-anti-affinity
    register: workerNet2Group
    when: net2 | default(false) | bool
